# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-08 09:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150, verbose_name='Логин')),
                ('first_name', models.CharField(max_length=150, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=150, verbose_name='Фамилия')),
                ('avatar', models.ImageField(upload_to='users_image', verbose_name='Аватар')),
                ('birth_date', models.DateField(verbose_name='Дата рождения')),
                ('rating', models.DecimalField(decimal_places=0, default=0, max_digits=2, verbose_name='Рейтинг')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
            },
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
