# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-08 12:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0002_auto_20171108_0947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='rating',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Рейтинг'),
        ),
    ]
