# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-03 13:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0002_auto_20171103_1300'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='likes', to='test_app.Like'),
        ),
    ]
